name: "(CI): Verify Build And Plan"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
      API_BASE_URL: "http://localhost:8000"
      API_KEY: "dummy"
      NEXT_PUBLIC_POSTHOG_KEY: "dummy"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_URL_INTERNAL: "http://localhost:3000"
      NEXTAUTH_SECRET: "dummy"
      GOOGLE_CLIENT_ID: "dummy"
      GOOGLE_CLIENT_SECRET: "dummy"
      JWT_SECRET: "dummy"
      OPENAI_API_KEY: "dummy"
      OPENAI_API_TOKEN_BASE_URL: "dummy"
      OPENAI_ORGANIZATION_ID: "dummy"
      OPENAI_PROJECT_ID: "dummy"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install PNPM
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run Build
        run: |
          pnpm run build
